### PR TITLE
Revamp App Screen

### PR DESCRIPTION
**Pull request by ramdhanymf**
Hi,

Thank you for letting me contribute to the app. Here are the changes applied:

1. Change looks on AppCard
2. Change looks on AppScreen

Please let me know if there are any questions, suggestions, inputs or anything.

### CODE REVIEW

**Comment by TripleSpeeder** [comment]
Please change the PR target to the DEV branch

**Review by TripleSpeeder — CHANGES_REQUESTED** [review]
I think there is a problem with filtering of apps.
When trying to enter a search string only the first letter is accepted. Then immediately the apps are filtered and my entered letter disappears.
- I can't enter another letter
- I don't see the letter I have entered

**Review by TripleSpeeder — CHANGES_REQUESTED** [review]
The UI needs to indicate if app linking is currently in progress. The old apps screen is showing this on top of the screen, if there is any app in 'pending' state, or if the user is waiting for sponsoring to be applied.
Look at https://github.com/BrightID/BrightID/blob/63923151ed089956b1e53aba024f717bfa7aba1a/BrightID/src/components/Apps/AppsScreen.tsx#L106

**Comment by damavara** [comment]
Hi

> The UI needs to indicate if app linking is currently in progress. The old apps screen is showing this on top of the screen, if there is any app in 'pending' state, or if the user is waiting for sponsoring to be applied. Look at
> 
> https://github.com/BrightID/BrightID/blob/63923151ed089956b1e53aba024f717bfa7aba1a/BrightID/src/components/Apps/AppsScreen.tsx#L106

Hi @TripleSpeeder, here is how we can show the progress
https://www.figma.com/proto/gj8yGWKB9hkm6PjBT5QueA/App-Improvement-2022?node-id=236%3A306&scaling=min-zoom&page-id=2%3A608&starting-point-node-id=236%3A306

@ramdhanymf @TripleSpeeder the css of the layout can be accessed on https://www.figma.com/file/gj8yGWKB9hkm6PjBT5QueA/App-Improvement-2022?node-id=2%3A608

**Pull request merged**
