### PR TITLE
Revamp Home Screen

### PR DESCRIPTION
**Pull request by ramdhanymf**
Hi,

Thank you for letting me contribute to the app. I just made changes to the Home Screen.

Please let me know if you have any changes, suggestions, input, or anything else.

### CODE REVIEW

**Review by TripleSpeeder — CHANGES_REQUESTED** [review]
The new home screen is missing two important elements:
- the currently connected node (which can be clicked to switch to another node)
- The client version 

Can you readd these elements?

**Comment by ramdhanymf** [comment]
> The new home screen is missing two important elements:
> 
> * the currently connected node (which can be clicked to switch to another node)
> * The client version

I think I need @damavara 's help to add the new design regarding the connected node and the client version.

**Comment by damavara** [comment]
Screen Shot 2022-06-21 at 11 15 59
we can add the node and version on the buttom but with a little tweak on the top part. >

**Comment by TripleSpeeder** [comment]
I will pick this up.

**Comment by TripleSpeeder** [comment]
Closing this outdated PR until someone takes on the task again.

**Pull request closed without merging**
